/** Admin dashboard metric keys (must match get_admin_dashboard_drilldown / SQL) */
export const DRILLDOWN_METRICS = {
	portfolio_active: 'portfolio_active',
	portfolio_defaulted: 'portfolio_defaulted',
	portfolio_general: 'portfolio_general',
	disbursed_monthly: 'disbursed_monthly',
	disbursed_yearly: 'disbursed_yearly',
	disbursed_overall: 'disbursed_overall',
	interest_disbursed_month: 'interest_disbursed_month',
	interest_disbursed_range: 'interest_disbursed_range',
	collected_month_principal: 'collected_month_principal',
	collected_month_interest: 'collected_month_interest',
	collected_month_total: 'collected_month_total',
	outstanding_principal: 'outstanding_principal',
	outstanding_interest: 'outstanding_interest',
	outstanding_total: 'outstanding_total',
	default_disbursed: 'default_disbursed',
	default_interest: 'default_interest',
	default_total: 'default_total',
	expected_today: 'expected_today',
	expected_tomorrow: 'expected_tomorrow',
	disbursed_today: 'disbursed_today',
	collected_today: 'collected_today',
	/** Borrowers registered by the officer (same scope as total_borrowers count) */
	my_borrowers: 'my_borrowers',
	/** Active loans whose last schedule installment falls within the next N days (default 14) */
	nearing_completion: 'nearing_completion',
};

export const METRIC_TITLES = {
	[DRILLDOWN_METRICS.portfolio_active]: 'Portfolio — Active loans',
	[DRILLDOWN_METRICS.portfolio_defaulted]: 'Portfolio — Defaulted',
	[DRILLDOWN_METRICS.portfolio_general]: 'Portfolio — General',
	[DRILLDOWN_METRICS.disbursed_monthly]: 'Disbursed principal — Monthly',
	[DRILLDOWN_METRICS.disbursed_yearly]: 'Disbursed principal — Yearly',
	[DRILLDOWN_METRICS.disbursed_overall]: 'Disbursed principal — Overall',
	[DRILLDOWN_METRICS.interest_disbursed_month]: 'Interest — Monthly',
	[DRILLDOWN_METRICS.interest_disbursed_range]: 'Interest — Date range',
	[DRILLDOWN_METRICS.collected_month_principal]: 'Collected — Principal',
	[DRILLDOWN_METRICS.collected_month_interest]: 'Collected — Interest',
	[DRILLDOWN_METRICS.collected_month_total]: 'Collected — Total (P+I)',
	[DRILLDOWN_METRICS.outstanding_principal]: 'Outstanding principal',
	[DRILLDOWN_METRICS.outstanding_interest]: 'Outstanding interest',
	[DRILLDOWN_METRICS.outstanding_total]: 'Outstanding total (P+I)',
	[DRILLDOWN_METRICS.default_disbursed]: 'Default — disbursed principal',
	[DRILLDOWN_METRICS.default_interest]: 'Default — interest amount',
	[DRILLDOWN_METRICS.default_total]: 'Default — total amount',
	[DRILLDOWN_METRICS.expected_today]: 'Expected today (installments due)',
	[DRILLDOWN_METRICS.expected_tomorrow]: 'Projected tomorrow (installments due)',
	[DRILLDOWN_METRICS.disbursed_today]: 'Disbursed today',
	[DRILLDOWN_METRICS.collected_today]: 'Collected today',
	[DRILLDOWN_METRICS.my_borrowers]: 'Borrowers Registered by you',
	[DRILLDOWN_METRICS.nearing_completion]: 'Nearing loan completion (final payment within days)',
};
